blog/config/routes.rb
Rails.application.routes.draw do
  resources :resumes do
    resources :skills
  end

  root 'welcome#index'
  get 'welcome/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/resume.rb
class Resume < ApplicationRecord
    has_many:skills
end

blog/app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :resume
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

blog/app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: %i[ show edit update destroy ]

  # GET /resumes or /resumes.json
  def index
    @resumes = Resume.all
  end

  # GET /resumes/1 or /resumes/1.json
  def show
  end

  # GET /resumes/new
  def new
    @resume = Resume.new
  end

  # GET /resumes/1/edit
  def edit
  end

  # POST /resumes or /resumes.json
  def create
    @resume = Resume.new(resume_params)

    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: "Resume was successfully created." }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resumes/1 or /resumes/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: "Resume was successfully updated." }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1 or /resumes/1.json
  def destroy
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to resumes_url, notice: "Resume was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def resume_params
      params.require(:resume).permit(:firstname, :lastname, :image_url, :role, :location, :email, :phone)
    end
end

blog/app/controllers/skills_controller.rb
class SkillsController < ApplicationController
 
    def create
        @resume = Resume.find(params[:resume_id])
        @skill = @resume.skills.create(skill_params)
        redirect_to resume_path(@resume)
    end
 
  private
    def skill_params
      params.require(:skill).permit(:skill_title, :skill_level)
    end
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def about
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/resumes_helper.rb
module ResumesHelper
end

blog/app/helpers/skills_helper.rb
module SkillsHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'>
    
  </head>
  

  <body>
    <%= yield %>
  </body>
</html>

blog/app/views/resumes/_form.html.erb
<%= form_for(resume) do |f| %>
  <% if resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% resume.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %>
    <%= f.text_field :firstname %>
  </div>

  <div class="field">
    <%= f.label :lastname %>
    <%= f.text_field :lastname %>
  </div>
  
  <div class="field">
    <%= f.label :role %>
    <%= f.text_field :role %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/resumes/edit.html.erb
<h1>Editing Resume</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

blog/app/views/resumes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resumes</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Image url</th>
      <th>Role</th>
      <th>Location</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= resume.firstname %></td>
        <td><%= resume.lastname %></td>
        <td><%= resume.image_url %></td>
        <td><%= resume.role %></td>
        <td><%= resume.location %></td>
        <td><%= resume.email %></td>
        <td><%= resume.phone %></td>
        <td><%= link_to 'Show', resume %></td>
        <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
        <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resume', new_resume_path %>

blog/app/views/resumes/new.html.erb
<h1>APPLY WITH YOUR INFORMATION!</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Back', resumes_path %>

blog/app/views/resumes/show.html.erb
<p id="notice"><%= notice %></p>

<h3>TELL US ABOUT YOU SKILLS!</h3>
<p>
  <strong>Firstname:</strong>
  <%= @resume.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @resume.lastname %>
</p>

<p>
  <strong>Role Applied for:</strong>
  <%= @resume.role %>
</p>

<p>
  <strong>Location Applied to:</strong>
  <%= @resume.location %>
</p>

<p>
  <strong>Email:</strong>
  <%= @resume.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @resume.phone %>
</p>


<%= form_for([@resume, @resume.skills.build]) do |f| %>
  <p>
    <%= f.label :skill_title %><br>
    <%= f.text_field :skill_title %>
  </p>
  <p>
    <%= f.label :skill_level %><br>
    <%= f.text_field :skill_level %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Edit', edit_resume_path(@resume) %>
<%= link_to 'Back', resumes_path %>
<br><br>


<h3><b>Applicant Information</b></h3>
<p><b>First Name:</b><%= @resume.firstname %></p>
<p><b>Last Name:</b><%= @resume.lastname %></p>
<p><b>Role Applied For:</b><%= @resume.role %></p>
<p><b>Location Applied to:</b><%= @resume.location %></p>
<p><b>E-mail:</b><%= @resume.email %></p>
<p><b>Phone Number:</b><%= @resume.phone %></p>
<br>

<h3><b>Applicant Skill Percentages</b></h3>
<p class="w3-small"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i></b></p>
  <% @resume.skills.each do |skill| %>
      <p><%= skill.skill_title %></p>
      <div class="w3-light-grey w3-round-xlarge w3-small">
        <div class="w3-container w3-center w3-round-xlarge w3-green" style="width:<%= skill.skill_level %>"><%= skill.skill_level %></div>
      </div>
  <% end %>

blog/app/views/welcome/about.html.erb
<%= link_to 'Main Page', root_path %><nav class="w3-sidebar w3-yellow w3-collapse w3-top w3-large w3-padding" style="z-index:3;width:300px;font-weight:bold;" id="mySidebar"><br>
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-button w3-hide-large w3-display-topleft" style="width:100%;font-size:22px">Close Menu</a>
  <div class="w3-container">
    <h3 class="w3-padding-64"><b>OZONE PARK</b></h3>
  </div>
  
  <!--   NAV BAR   -->
  <div class="w3-bar-block">
    <a href="#history" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-green">History</a> 
    <a href="#parks" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-green">Park and Recreation</a> 
    <a href="#films" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-green">Filmography</a> 
    <a href="#residents" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-green">Famous Residents</a> 
    <a href="#aqueduct" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-green">Aqueduct Racetrack</a> 
    <a href="<%=new_resume_path %>" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-green">Apply Here</a> 
  </div>
</nav>

<!-- Top menu on small screens -->
<header class="w3-container w3-top w3-hide-large w3-yellow w3-xlarge w3-padding">
  <a href="javascript:void(0)" class="w3-button w3-green w3-margin-right" onclick="w3_open()">☰</a>
  <span>Ozone Park</span>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>



<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:340px;margin-right:40px">

  <div class="w3-container" id="history" style="margin-top:75px">
    <h1 class="w3-xxxlarge w3-text-green"><b>History</b></h1>
    <hr style="width:50px;border:5px solid black" class="w3-round">
    <br><br>
    <div class="w3">
      <%= image_tag("pictures/house.jpg", :style=> "width:35%", :onClick=>"onClick(this)", :alt=>"house")%>
      <br><br>
      <p>According to historical narratives, the Native Americans of the Jameco and Rockaway tribes were the first original settlers in the area that would eventually become Ozone Park. There was no borough of Queens in the 1860s, only the counties of Kings and Queens sitting near each other on the western end of Long Island. The county of Queens was sparsely populated outside of a few towns further north, including Flushing, Jamaica, Astoria and Newtown (later Elmhurst). In 1880, the Long Island Railroad built a station south of Woodhaven as part of its line from Long Island City to Howard Beach. Two years later, two speculators Benjamin W. Hitchcock and Charles C. Denton bought up most of the plots of land around the station and began marketing the area as a visionary new neighborhood called Ozone Park!
        It was then that music publisher and developer Benjamin Hitchcock, the developer of Ozone Park, along with fellow partner Charles Denton, began converting farmland in the area into parking lots. From there, they began marketing the area to the south of Ozone Park for its “invigorating and healthful” breezes sweeping in from Jamaica Bay and the Atlantic Ocean—which fatefully led to the name ‘Ozone Park’ being chosen for the area. Soon after, in 1907, real estate developer David Leahy, known to some as “the Father of South Ozone Park” began building small homes in former farm fields by promising potential home owners that for $9 down, $6 per month, they could purchase a four-room cottage in the country. Knowing of the future expansion of the former Pennsylvania Railroad, purchased by the Long Island Rail Road in 1900, into the Jamaica area, Leahy anticipated that more and more people would be eager to move to South Ozone Park, thereby selling properties at an affordable price to attract settlers.</p>
      <br><br>
      <%= image_tag("pictures/ozone_about.jpg", :style=> "width:30%", :onClick=>"onClick(this)", :alt=>"house")%>
      <br><br>
      
      <p>Since that time, Ozone Park has grown into a key part of Queens—home to the Aqueduct Racetrack, a casino, and maybe even soon the largest convention center in the nation, courtesy of the Genting Group—with a diverse demographic of roughly 45,000 residents that includes Hispanics, African-Americans, Italians, South Asians, people from the West Indies and South Americans. In previous years, Ozone Park had been a hub for mafia activity for the Gambino and Lucchese crime families, both of which ran operations based out of Ozone Park prior to law enforcement cracking down with various gang-busting operations. In fact, Bergin Hunt and Fish Club, the Gambino family’s headquarters, was right in the heart of Ozone Park, at 98-04 101st Avenue. The property houses a pet grooming boutique and a medical supply store now, but if walls could talk, we’re pretty confident they could make the parakeets blush, just a little.</p>
      
    
    </div>
    </p>
  </div>
  

  
  <div class="w3-container" id="parks" style="margin-top:75px">
    <h1 class="w3-xxxlarge w3-text-green"><b>Parks and Recreation</b></h1>
    <hr style="width:50px;border:5px solid black" class="w3-round">
    <br><br>
       <div class="w3">
      <%= image_tag("pictures/forest-park.jpg", :style=> "width:35%", :onClick=>"onClick(this)", :alt=>"house")%>
      <br><br>
      <h3><b>Forest Park</b></h3>
      <p>Myrtle Avenue and Woodhaven Blvd</p>
      <p>Woodhaven, NY 11385</p>
      <p>Although technically not in Ozone Park, Forest Park is on the border with Ozone Park and worth mentioning. Goers interested in exploring Forest Park’s natural settings firsthand often travel to its eastern portion, which abounds in hiking trails and bridle paths.</p>

</p><br><br>
      <%= image_tag("pictures/Maurice-park.jpg", :style=> "width:35%", :onClick=>"onClick(this)", :alt=>"house")%>
      <br><br>
      <h3><b>Maurice A Fitzgerald Park</b></h3>
      <p>106TH Street Between Atlantic Ave</p>
      <p>Ozone Park, NY 11416</p>
      <p>This NYC outdoor playground is equipped with basketball courts, children swings, handball courts, spray showers and with working facilities. There were an abundant of adult swings in the 1980s, but unfortunately these have been eradicated for the an increase of basketball and hand ball courts in the 1990s.</p>
    
    </div>
  </div>
  
  <!-- Modal for full size images on click-->
  <div id="modal01" class="w3-modal w3-black" style="padding-top:0" onclick="this.style.display='none'">
    <span class="w3-button w3-black w3-xxlarge w3-display-topright">×</span>
    <div class="w3-modal-content w3-animate-zoom w3-center w3-transparent w3-padding-64">
      <img id="img01" class="w3-image">
      <p id="caption"></p>
    </div>
  </div>

  <!-- Services -->
  <div class="w3-container" id="films" style="margin-top:75px">
    <h1 class="w3-xxxlarge w3-text-green"><b>Filmography</b></h1>
    <hr style="width:50px;border:5px solid black" class="w3-round">
    <br><br>
    
       <div class="w3">
      <%= image_tag("pictures/Goodfellas.jpg", :style=> "width:25%", :onClick=>"onClick(this)", :alt=>"house")%>
      <br><br>
      <h3><b>Goodfellas</b></h3>
      <p>1990</p>
      <p>Is an Academy Award-winning gangster film that takes place in and around Ozone Park. Goodfellas is an American crime film directed by Martin Scorsese. It is an adaptation of the 1985 non-fiction book Wiseguy by Nicholas Pileggi. The film narrates the rise and fall of mob associate Henry Hill and his friends and family from 1955 to 1980.
      </p><br><br>
      
      <%= image_tag("pictures/bronxtale.jpg", :style=> "width:25%", :onClick=>"onClick(this)", :alt=>"house")%>
      <br><br>
       <h3><b>A Bronx Tale</b></h3>
      <p>2001</p>
      <p>A Bronx Tale features a scene set at Aqueduct Racetrack in Ozone Park. It is an American crime drama film, adapted from Chazz Palminteri's 1989 play of the same name. It tells the coming of age story of an Italian-American boy, Calogero Anello, who, after encountering a local Mafia boss, is torn between the temptations of organized crime and the values of his honest, hardworking father.
      </p><br><br>
      
      <%= image_tag("pictures/Boss_of_Bosses.jpg", :style=> "width:25%", :onClick=>"onClick(this)", :alt=>"house")%>
      <br><br>
      <h3><b>Boss of Bosses</b></h3>
      <p>2001</p>
      <p>It features a scene with John Gotti in Ozone Park at the Bergin Hunt and Fish Club. Boss of Bosses is a an American made-for-TV movie about the life of former Gambino crime family boss Paul Castellano directed by Dwight H. Little. It stars Chazz Palminteri as Paul Castellano, Patricia Mauceri as his wife Nina, Mark Margolis as Joseph Armone, and Angela Alvarado as his mistress Gloria Olarte.</p>
    </div>
  </div>
  
  <!-- Designers -->
  <div class="w3-container" id="residents" style="margin-top:75px">
    <h1 class="w3-xxxlarge w3-text-green"><b>Famous Residents</b></h1>
    <hr style="width:50px;border:5px solid black" class="w3-round">
    <br><br>
       <div class="w3">
      <%= image_tag("pictures/Carol_Heiss_1960.jpg", :style=> "width:30%", :onClick=>"onClick(this)", :alt=>"house")%>
      <br><br>
      <h3><b>Carol Heiss</b></h3>
      <p>January 20, 1940</p>
      <p>Carol Elizabeth Heiss Jenkins (born January 20, 1940) is an American former figure skater and actress. Competing in ladies' singles, she became the 1960 Olympic champion, the 1956 Olympic silver medalist, and a five-time World champion (1956–1960).Carol Heiss was born on January 20, 1940, in New York City, and grew up Ozone Park, Queens.
      </p><br><br>
      
      <%= image_tag("pictures/Joseph_P._Addabbo.jpg", :style=> "width:30%", :onClick=>"onClick(this)", :alt=>"house")%>
      <br><br>
      <h3><b>Joseph P. Addabbo</b></h3>
      <p>March 17, 1925 – April 10, 1986</p>
      <p>He was a New York City politician who served as a Democrat in the United States House of Representatives from 1961 until his death from a seizure in Washington, D.C. in 1986. As the chairman of the United States House Appropriations Subcommittee on Defense in the 1980s, he was a noted critic of President Ronald Reagan's massive defense spending increases. Addabbo was born in Queens, New York and lived in the borough his entire life.
      </p><br><br>
      
      <%= image_tag("pictures/John_Gotti.jpg", :style=> "width:45%", :onClick=>"onClick(this)", :alt=>"house")%>
      <br><br>
      <h3><b>John Gotti</b></h3>
      <p>October 27, 1940 – June 10, 2002</p>
      <p>He was an Italian-American gangster who became boss of the Gambino crime family in New York City. He became one of the crime family's biggest earners and a protégé of Gambino family underboss Aniello Dellacroce, operating out of the Ozone Park neighborhood of Queens. While his peers avoided attracting attention, especially from the media, Gotti became known as "The Dapper Don".</p>
      <br><br>
    </div>
  </div>

 <div class="w3-container" id="aqueduct" style="margin-top:75px">
    <h1 class="w3-xxxlarge w3-text-green"><b>Aqueduct Racetrack</b></h1>
    <hr style="width:50px;border:5px solid black" class="w3-round">
    <br><br>
      <div class="w3">
      <%= image_tag("pictures/racetrack1.jpg", :style=> "width:75%", :onClick=>"onClick(this)", :alt=>"house")%>
      <br><br>
       <h3><b>AQUEDUCT RACETRACK</b></h3>
      <p>110-00 Rockaway Blvd</p>
      <p>Ozone Park, NY 11420</p>
      <p>Aqueduct Racetrack, also known as the Big A, is the only racetrack in New York City, occupying 210 acres in South Ozone Park in the borough of Queens. Since 2013, the New York Racing Association has invested more than $18 million in capital improvements at Aqueduct, showcasing a continued focus on enhancing the guest experience and improving the quality of racing. One of the most transformational additions was the opening of Longshots, a state-of-the-art simulcasting center and sports bar. Additional improvements include the installation of hundreds of new HD televisions and new HD video boards across the property. In 2017, NYRA embarked on the most significant reconstruction project of the racing surfaces since 1975, replacing the inner dirt course with a second turf course, installing a state-of-the-art irrigation system, and renovating the main track to facilitate year round racing.</p>
      
    </div>
  </div>


<br><br>
<a href="#history" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-green" style="float:left">Back to the Top</a> 


<!-- End page content -->
</div>


<!-- W3.CSS Container -->
<div class="w3-light-grey w3-container w3-padding-32" style="margin-top:75px;padding-right:58px;width:100%">
   <%= link_to root_path do %>
     <p style="float:right;text-decoration:underline"> Back to Main Page</p>
   <%end%>
</div>

blog/app/views/welcome/index.html.erb
<div class="w3-display-container" style="margin-bottom:50px">
  <%= image_tag("pictures/intropark_welcome.jpg", :style=> "width:100%")%>
  <div class="w3-display-bottomleft w3-container w3-amber w3-hover-orange w3-hide-small"
   style="bottom:30%;opacity:0.8;width:50%">
  <h1><p>WELCOME TO </p><h1><b>OZONE PARK</b></h1>
</div>


</div>

<div class="w3-row w3-container" style="margin:50px 0"> 
<div class="w3-half w3-container">
  <div class="w3-topbar w3-border-amber">
    <%= link_to welcome_about_path do %>
      <%= image_tag("pictures/history_welcome.jpg", :style=> "width:100%")%>
    <%end%>
    <br><br><h2><b>History of Ozone Park</b></h2>
    <p><i style="color:darkgoldenrod">Learn about Ozone Park's rich history</i></p>
  </div>
</div>

<div class="w3-half w3-container">
  <div class="w3-topbar w3-border-amber">
    <%= link_to welcome_about_path do %>
    <%= image_tag("pictures/parks_welcome.jpg", :style=> "width:100%")%>
    <%end%>
    <h2><b>Parks and Recreation</b></h2>
    <p><i style="color:darkgoldenrod">View the beautiful parks in the neighborhood.</i></p>
  </div>
</div>
</div>

<div class="w3-row w3-container" style="margin:50px 0">
<div class="w3-half w3-container">
  <div class="w3-topbar w3-border-orange">
    <%= link_to welcome_about_path do %>
    <%= image_tag("pictures/goodfellas_welcome.jpg", :style=> "width:100%")%>
    <%end%>
    <h2><b>Filmography</b></h2>
    <p><i style="color:darkgoldenrod">View some of the films shot in Ozone Park</i> </p>
  </div>
</div>

<div class="w3-half w3-container">
  <div class="w3-topbar w3-border-orange">
    <%= link_to welcome_about_path do %>
    <%= image_tag("pictures/gotti_welcome.jpg", :style=> "width:100%")%>
    <%end%>
    <h2><b>Famous Residents</b></h2>
    <p><i style="color:darkgoldenrod">Learn about some of the famous people who have lived in Ozone Park.</i></p>
    </div>
</div>
</div>

<div class="w3-row w3-container" style="margin:50px 0">
<div class="w3-half w3-container">
  <div class="w3-topbar w3-border-orange">
    <%= link_to welcome_about_path do %>
    <%= image_tag("pictures/aqueduct_welcome.jpg", :style=> "width:100%")%>
    <%end%>
    <h2><b>Aqueduct Racetrack</b></h2>
    <p><i style="color:darkgoldenrod">Eager to place a bet ? Visit the Racetrack!</i></p>
  </div>
</div>

<div class="w3-half w3-container">
  <div class="w3-topbar w3-border-orange">
    <%= link_to new_resume_path do %>
    <%= image_tag("pictures/apply_welcome.jpg", :style=> "width:100%")%>
    <%end%>
    
    <h2><b>Apply here</b></h2>
    <p><i style="color:darkgoldenrod">Don't wait until it is to late.</i></p>
    </div>
</div>
</div>

<%= link_to 'History', welcome_about_path %>